// Equipment types and interfaces

export interface Equipment {
  id: number;
  description: string;
  model: string | null;
  serial_number: string | null;
  linked_serials: string | null;
  brand_name: string;
  subfamily_name: string;
  customer_name: string;
}

export interface EquipmentDetail {
  id: number;
  description: string;
  customer_id: number;
  brand_id: number;
  model: string | null;
  serial_number: string | null;
  sale_date: string | null;
  flg_not_sold_by_saded: boolean;
  group_id: string | null;
  subgroup_id: string | null;
  note: string | null;
  tech_assist_phone_num: string | null;
  fl_gas: boolean;
  compressor_type_id: number | null;
  gas_type_id: number | null;
  max_charge: string | null;
  compr_model: string | null;
  compr_brand: string | null;
  compr_unique_num: string | null;
  fgas_check_date: string | null;
  periodic_checks: string;
  tech_sheet_url: string | null;
  tech_sheet_uploaded_at: string | null;
  machine_design_url: string | null;
  machine_design_uploaded_at: string | null;
  electrical_diagram_url: string | null;
  electrical_diagram_uploaded_at: string | null;
  service_manual_url: string | null;
  service_manual_uploaded_at: string | null;
  instruction_manual_url: string | null;
  instruction_manual_uploaded_at: string | null;
  created_at: string;
  updated_at: string;
  grouping: string | null;
  design_position: string | null;
  family_id: string;
  subfamily_id: string;
  customer_location_id: number | null;
  group_label: string;
  brand_label: string;
  subgroup_label: string | null;
  gas_type_label: string | null;
  compressor_type_label: string | null;
  company_name: string;
  location_company_name: string | null;
  family_label: string;
  subfamily_label: string;
  images: EquipmentImage[];
  linked_equipments: LinkedEquipment[];
}

export interface EquipmentImage {
  id: number;
  equipment_id: number;
  image_url: string;
  image_name: string;
  uploaded_at: string;
}

export interface LinkedEquipment {
  id: number;
  description: string;
  model: string | null;
  serial_number: string | null;
  brand_name: string;
}

export interface EquipmentsApiResponse {
  data: Equipment[];
  meta: {
    total: number;
    page: number;
    skip: number;
    totalPages: number;
  };
}

export interface EquipmentQueryParams {
  page?: string;
  skip?: string;
  customer_id?: string;
  customer_location_id?: string;
  query?: string;
}

// Complete request body for POST (create equipment)
export interface CreateEquipmentRequest {
  id?: number; // Optional for POST, will be generated by backend
  description: string;
  customer_id: number;
  brand_id: number;
  model?: string | null;
  serial_number?: string | null;
  sale_date?: string | null; // ISO date string (YYYY-MM-DD)
  flg_not_sold_by_saded?: boolean;
  group_id?: number | null;
  subgroup_id?: number | null;
  note?: string | null;
  tech_assist_phone_num?: string | null;
  fl_gas?: boolean;
  compressor_type_id?: number | null;
  gas_type_id?: number | null;
  max_charge?: string | null;
  compr_model?: string | null;
  compr_brand?: string | null;
  compr_unique_num?: string | null;
  fgas_check_date?: string | null; // ISO date string (YYYY-MM-DD)
  periodic_checks?: string | null;
  tech_sheet_url?: string | null;
  tech_sheet_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  machine_design_url?: string | null;
  machine_design_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  electrical_diagram_url?: string | null;
  electrical_diagram_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  service_manual_url?: string | null;
  service_manual_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  instruction_manual_url?: string | null;
  instruction_manual_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  created_at?: string; // ISO datetime string, usually set by backend
  updated_at?: string; // ISO datetime string, usually set by backend
}

// Complete request body for PUT (update equipment)
export interface UpdateEquipmentRequest {
  id: number; // Required for PUT
  description?: string;
  customer_id?: number;
  brand_id?: number;
  model?: string | null;
  serial_number?: string | null;
  sale_date?: string | null; // ISO date string (YYYY-MM-DD)
  flg_not_sold_by_saded?: boolean;
  group_id?: number | null;
  subgroup_id?: number | null;
  note?: string | null;
  tech_assist_phone_num?: string | null;
  fl_gas?: boolean;
  compressor_type_id?: number | null;
  gas_type_id?: number | null;
  max_charge?: string | null;
  compr_model?: string | null;
  compr_brand?: string | null;
  compr_unique_num?: string | null;
  fgas_check_date?: string | null; // ISO date string (YYYY-MM-DD)
  periodic_checks?: string | null;
  tech_sheet_url?: string | null;
  tech_sheet_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  machine_design_url?: string | null;
  machine_design_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  electrical_diagram_url?: string | null;
  electrical_diagram_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  service_manual_url?: string | null;
  service_manual_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  instruction_manual_url?: string | null;
  instruction_manual_uploaded_at?: string | null; // ISO date string (YYYY-MM-DD)
  created_at?: string; // ISO datetime string, usually not updated
  updated_at?: string; // ISO datetime string, usually set by backend
}

// Utility type for equipment form data (frontend use)
export interface EquipmentFormData {
  description: string;
  customer_id: number;
  brand_id: number;
  model?: string;
  serial_number?: string;
  sale_date?: string;
  flg_not_sold_by_saded?: boolean;
  group_id?: number;
  subgroup_id?: number;
  note?: string;
  tech_assist_phone_num?: string;
  fl_gas?: boolean;
  compressor_type_id?: number;
  gas_type_id?: number;
  max_charge?: string;
  compr_model?: string;
  compr_brand?: string;
  compr_unique_num?: string;
  fgas_check_date?: string;
  periodic_checks?: string;
} 